const express=require('express');
const {v4:uuid}=require('uuid');
const db=require('../db');
const {requireAuth,optionalAuth}=require('../middleware/auth');
const router=express.Router();
function authorInfo(authorId){const user=db.get('users').find({id:authorId}).value();return user?{id:user.id,username:user.username}:{id:authorId,username:'Unknown'};}
function serializePost(post,{withComments=false}={}){const base={id:post.id,title:post.title,content:post.content,author:authorInfo(post.authorId),createdAt:post.createdAt,updatedAt:post.updatedAt,commentCount:db.get('comments').filter({postId:post.id}).size().value()};if(withComments)base.comments=db.get('comments').filter({postId:post.id}).sortBy('createdAt').map(c=>({id:c.id,content:c.content,author:authorInfo(c.authorId),createdAt:c.createdAt})).value();return base;}
router.get('/',optionalAuth,(req,res)=>{const posts=db.get('posts').sortBy('createdAt').value().reverse().map(p=>serializePost(p));res.json({posts});});
router.get('/:id',optionalAuth,(req,res)=>{const post=db.get('posts').find({id:req.params.id}).value();if(!post)return res.status(404).json({error:'Post not found.'});res.json({post:serializePost(post,{withComments:true})});});
router.post('/',requireAuth,(req,res)=>{const{title,content}=req.body||{};if(!title||!content)return res.status(400).json({error:'A title and some content are required.'});const now=new Date().toISOString();const post={id:uuid(),authorId:req.user.id,title:title.trim(),content:content.trim(),createdAt:now,updatedAt:now};db.get('posts').push(post).write();res.status(201).json({post:serializePost(post)});});
router.put('/:id',requireAuth,(req,res)=>{const post=db.get('posts').find({id:req.params.id}).value();if(!post)return res.status(404).json({error:'Post not found.'});if(post.authorId!==req.user.id)return res.status(403).json({error:'You can only edit your own posts.'});const{title,content}=req.body||{};if(!title||!content)return res.status(400).json({error:'A title and some content are required.'});db.get('posts').find({id:req.params.id}).assign({title:title.trim(),content:content.trim(),updatedAt:new Date().toISOString()}).write();const updated=db.get('posts').find({id:req.params.id}).value();res.json({post:serializePost(updated)});});
router.delete('/:id',requireAuth,(req,res)=>{const post=db.get('posts').find({id:req.params.id}).value();if(!post)return res.status(404).json({error:'Post not found.'});if(post.authorId!==req.user.id)return res.status(403).json({error:'You can only delete your own posts.'});db.get('posts').remove({id:req.params.id}).write();db.get('comments').remove({postId:req.params.id}).write();res.json({ok:true});});
router.post('/:id/comments',requireAuth,(req,res)=>{const post=db.get('posts').find({id:req.params.id}).value();if(!post)return res.status(404).json({error:'Post not found.'});const{content}=req.body||{};if(!content||!content.trim())return res.status(400).json({error:'Comment cannot be empty.'});const comment={id:uuid(),postId:req.params.id,authorId:req.user.id,content:content.trim(),createdAt:new Date().toISOString()};db.get('comments').push(comment).write();res.status(201).json({comment:{id:comment.id,content:comment.content,author:authorInfo(comment.authorId),createdAt:comment.createdAt}});});
router.delete('/:postId/comments/:commentId',requireAuth,(req,res)=>{const comment=db.get('comments').find({id:req.params.commentId,postId:req.params.postId}).value();if(!comment)return res.status(404).json({error:'Comment not found.'});if(comment.authorId!==req.user.id)return res.status(403).json({error:'You can only delete your own comments.'});db.get('comments').remove({id:req.params.commentId}).write();res.json({ok:true});});
module.exports=router;
